services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
      - payment-service
      - notification-service
    networks:
      - backend

  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    networks:
      - backend

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    networks:
      - backend

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"
    networks:
      - backend

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - backend
  payment-service:
    build: ./payment-service
    ports:
      - "5004:5004"
    networks:
      - backend

  notification-service:
    build: ./notification-service
    ports:
      - "5005:5005"
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
