services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    networks:
      - backend

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    networks:
      - backend

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"
    networks:
      - backend

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - backend

networks:
  backend:
