version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    networks:
      - backend

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    networks:
      - backend

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"
    networks:
      - backend

networks:
  backend:
